[build]
  command = "cd modelina-website && npm ci && npm run build:modelina && npm run build"
  publish = "modelina-website/.next"

[build.environment]
  NODE_VERSION = "16.13.2"
  NPM_VERSION = "8.1.2"
  NEXT_PUBLIC_API_PATH = "/.netlify/functions"

[functions]
  directory = "modelina-website/.next/server/pages/api"

